server:
  port: 8081

cache:
  algorithm: lfu
  capacity: 15

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clever_lab_task_14_test?stringtype=unspecified
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true