server:
  port: 8080

cache:
  algorithm: lfu
  capacity: 15

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clever_lab_task_14?stringtype=unspecified
    username: root
    password: root
  liquibase:
    enabled: false
    change-log: changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /api/doc/